namespace Garrison.Shared.Config
{
    public enum ConfigKey
    {
        PlayerCount = 0,
        MoveSpeed = 1,
        CameraZoom = 2,
        CameraPushExtent = 3,
        CameraPushShape = 4,
        CameraPushHorizontalScale = 5,
        CameraPushForwardScale = 6,
        CameraPushBackwardScale = 7,
        CameraSafeViewportInset = 8,
        CameraReturn = 9,
        CameraReturnSpeed = 10,
        CameraPushCoupling = 11,
        SprintSpeed = 12,
        DefenderSlot = 13,
        BodyTurnSpeed = 14,
        AimLineWidth = 15,
        AimLineLength = 16,
        MaxHearts = 17,
        BleedOutSec = 18,
        AccuracyIdleSpread = 19,
        AccuracyMovingSpread = 20,
        AccuracySprintSpread = 21,
        WeaponDamageHearts = 22,
        WeaponBaseSpread = 23,
        WeaponRange = 24,
        WeaponFalloff = 25,
        RecoilPerShot = 26,
        RecoilMax = 27,
        RecoilSettleTime = 28,
        DefenderMaxHearts = 29,
        SyretteReachRadius = 30,
        ViewDistance = 31,
        LosTickRate = 32,
        NpcConeArc = 33,
        NpcConeRange = 34
    }
}
